# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eventstore/event_store.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='eventstore/event_store.proto',
  package='eventstore',
  syntax='proto3',
  serialized_options=b'Z*github.com/kfelter/grpc-example/eventstore',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x65ventstore/event_store.proto\x12\neventstore\"2\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04tags\x18\x02 \x03(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\".\n\tEventList\x12!\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x11.eventstore.Event\"\x1f\n\x0fGetEventRequest\x12\x0c\n\x04tags\x18\x02 \x03(\t\"%\n\x13StoreEventsResponse\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x17\n\x15ServerMestricsRequest\"\x85\x01\n\x15ServerMetricsResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1e\n\x16\x61vg_get_query_duration\x18\x02 \x01(\t\x12\x1a\n\x12\x61vg_store_duration\x18\x03 \x01(\t\x12\x12\n\nlen_events\x18\x04 \x01(\x03\x12\x0c\n\x04size\x18\x05 \x01(\t2\xed\x01\n\nEventStore\x12?\n\tGetEvents\x12\x1b.eventstore.GetEventRequest\x1a\x11.eventstore.Event\"\x00\x30\x01\x12\x45\n\x0bStoreEvents\x12\x11.eventstore.Event\x1a\x1f.eventstore.StoreEventsResponse\"\x00(\x01\x12W\n\rServerMetrics\x12!.eventstore.ServerMestricsRequest\x1a!.eventstore.ServerMetricsResponse\"\x00\x42,Z*github.com/kfelter/grpc-example/eventstoreb\x06proto3'
)




_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='eventstore.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='eventstore.Event.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tags', full_name='eventstore.Event.tags', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='eventstore.Event.content', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=94,
)


_EVENTLIST = _descriptor.Descriptor(
  name='EventList',
  full_name='eventstore.EventList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='events', full_name='eventstore.EventList.events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=142,
)


_GETEVENTREQUEST = _descriptor.Descriptor(
  name='GetEventRequest',
  full_name='eventstore.GetEventRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tags', full_name='eventstore.GetEventRequest.tags', index=0,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=175,
)


_STOREEVENTSRESPONSE = _descriptor.Descriptor(
  name='StoreEventsResponse',
  full_name='eventstore.StoreEventsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='eventstore.StoreEventsResponse.status', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=214,
)


_SERVERMESTRICSREQUEST = _descriptor.Descriptor(
  name='ServerMestricsRequest',
  full_name='eventstore.ServerMestricsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=239,
)


_SERVERMETRICSRESPONSE = _descriptor.Descriptor(
  name='ServerMetricsResponse',
  full_name='eventstore.ServerMetricsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='eventstore.ServerMetricsResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='avg_get_query_duration', full_name='eventstore.ServerMetricsResponse.avg_get_query_duration', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='avg_store_duration', full_name='eventstore.ServerMetricsResponse.avg_store_duration', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='len_events', full_name='eventstore.ServerMetricsResponse.len_events', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='eventstore.ServerMetricsResponse.size', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=375,
)

_EVENTLIST.fields_by_name['events'].message_type = _EVENT
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['EventList'] = _EVENTLIST
DESCRIPTOR.message_types_by_name['GetEventRequest'] = _GETEVENTREQUEST
DESCRIPTOR.message_types_by_name['StoreEventsResponse'] = _STOREEVENTSRESPONSE
DESCRIPTOR.message_types_by_name['ServerMestricsRequest'] = _SERVERMESTRICSREQUEST
DESCRIPTOR.message_types_by_name['ServerMetricsResponse'] = _SERVERMETRICSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'eventstore.event_store_pb2'
  # @@protoc_insertion_point(class_scope:eventstore.Event)
  })
_sym_db.RegisterMessage(Event)

EventList = _reflection.GeneratedProtocolMessageType('EventList', (_message.Message,), {
  'DESCRIPTOR' : _EVENTLIST,
  '__module__' : 'eventstore.event_store_pb2'
  # @@protoc_insertion_point(class_scope:eventstore.EventList)
  })
_sym_db.RegisterMessage(EventList)

GetEventRequest = _reflection.GeneratedProtocolMessageType('GetEventRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETEVENTREQUEST,
  '__module__' : 'eventstore.event_store_pb2'
  # @@protoc_insertion_point(class_scope:eventstore.GetEventRequest)
  })
_sym_db.RegisterMessage(GetEventRequest)

StoreEventsResponse = _reflection.GeneratedProtocolMessageType('StoreEventsResponse', (_message.Message,), {
  'DESCRIPTOR' : _STOREEVENTSRESPONSE,
  '__module__' : 'eventstore.event_store_pb2'
  # @@protoc_insertion_point(class_scope:eventstore.StoreEventsResponse)
  })
_sym_db.RegisterMessage(StoreEventsResponse)

ServerMestricsRequest = _reflection.GeneratedProtocolMessageType('ServerMestricsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SERVERMESTRICSREQUEST,
  '__module__' : 'eventstore.event_store_pb2'
  # @@protoc_insertion_point(class_scope:eventstore.ServerMestricsRequest)
  })
_sym_db.RegisterMessage(ServerMestricsRequest)

ServerMetricsResponse = _reflection.GeneratedProtocolMessageType('ServerMetricsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERVERMETRICSRESPONSE,
  '__module__' : 'eventstore.event_store_pb2'
  # @@protoc_insertion_point(class_scope:eventstore.ServerMetricsResponse)
  })
_sym_db.RegisterMessage(ServerMetricsResponse)


DESCRIPTOR._options = None

_EVENTSTORE = _descriptor.ServiceDescriptor(
  name='EventStore',
  full_name='eventstore.EventStore',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=378,
  serialized_end=615,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetEvents',
    full_name='eventstore.EventStore.GetEvents',
    index=0,
    containing_service=None,
    input_type=_GETEVENTREQUEST,
    output_type=_EVENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StoreEvents',
    full_name='eventstore.EventStore.StoreEvents',
    index=1,
    containing_service=None,
    input_type=_EVENT,
    output_type=_STOREEVENTSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ServerMetrics',
    full_name='eventstore.EventStore.ServerMetrics',
    index=2,
    containing_service=None,
    input_type=_SERVERMESTRICSREQUEST,
    output_type=_SERVERMETRICSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVENTSTORE)

DESCRIPTOR.services_by_name['EventStore'] = _EVENTSTORE

# @@protoc_insertion_point(module_scope)
