// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package eventstore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EventStoreClient is the client API for EventStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventStoreClient interface {
	GetEvents(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (EventStore_GetEventsClient, error)
	StoreEvents(ctx context.Context, opts ...grpc.CallOption) (EventStore_StoreEventsClient, error)
	ServerMetrics(ctx context.Context, in *ServerMestricsRequest, opts ...grpc.CallOption) (*ServerMetricsResponse, error)
}

type eventStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewEventStoreClient(cc grpc.ClientConnInterface) EventStoreClient {
	return &eventStoreClient{cc}
}

func (c *eventStoreClient) GetEvents(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (EventStore_GetEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &EventStore_ServiceDesc.Streams[0], "/eventstore.EventStore/GetEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventStoreGetEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EventStore_GetEventsClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type eventStoreGetEventsClient struct {
	grpc.ClientStream
}

func (x *eventStoreGetEventsClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *eventStoreClient) StoreEvents(ctx context.Context, opts ...grpc.CallOption) (EventStore_StoreEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &EventStore_ServiceDesc.Streams[1], "/eventstore.EventStore/StoreEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventStoreStoreEventsClient{stream}
	return x, nil
}

type EventStore_StoreEventsClient interface {
	Send(*Event) error
	CloseAndRecv() (*StoreEventsResponse, error)
	grpc.ClientStream
}

type eventStoreStoreEventsClient struct {
	grpc.ClientStream
}

func (x *eventStoreStoreEventsClient) Send(m *Event) error {
	return x.ClientStream.SendMsg(m)
}

func (x *eventStoreStoreEventsClient) CloseAndRecv() (*StoreEventsResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StoreEventsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *eventStoreClient) ServerMetrics(ctx context.Context, in *ServerMestricsRequest, opts ...grpc.CallOption) (*ServerMetricsResponse, error) {
	out := new(ServerMetricsResponse)
	err := c.cc.Invoke(ctx, "/eventstore.EventStore/ServerMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventStoreServer is the server API for EventStore service.
// All implementations must embed UnimplementedEventStoreServer
// for forward compatibility
type EventStoreServer interface {
	GetEvents(*GetEventRequest, EventStore_GetEventsServer) error
	StoreEvents(EventStore_StoreEventsServer) error
	ServerMetrics(context.Context, *ServerMestricsRequest) (*ServerMetricsResponse, error)
	mustEmbedUnimplementedEventStoreServer()
}

// UnimplementedEventStoreServer must be embedded to have forward compatible implementations.
type UnimplementedEventStoreServer struct {
}

func (UnimplementedEventStoreServer) GetEvents(*GetEventRequest, EventStore_GetEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedEventStoreServer) StoreEvents(EventStore_StoreEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method StoreEvents not implemented")
}
func (UnimplementedEventStoreServer) ServerMetrics(context.Context, *ServerMestricsRequest) (*ServerMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerMetrics not implemented")
}
func (UnimplementedEventStoreServer) mustEmbedUnimplementedEventStoreServer() {}

// UnsafeEventStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventStoreServer will
// result in compilation errors.
type UnsafeEventStoreServer interface {
	mustEmbedUnimplementedEventStoreServer()
}

func RegisterEventStoreServer(s grpc.ServiceRegistrar, srv EventStoreServer) {
	s.RegisterService(&EventStore_ServiceDesc, srv)
}

func _EventStore_GetEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetEventRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventStoreServer).GetEvents(m, &eventStoreGetEventsServer{stream})
}

type EventStore_GetEventsServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type eventStoreGetEventsServer struct {
	grpc.ServerStream
}

func (x *eventStoreGetEventsServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _EventStore_StoreEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventStoreServer).StoreEvents(&eventStoreStoreEventsServer{stream})
}

type EventStore_StoreEventsServer interface {
	SendAndClose(*StoreEventsResponse) error
	Recv() (*Event, error)
	grpc.ServerStream
}

type eventStoreStoreEventsServer struct {
	grpc.ServerStream
}

func (x *eventStoreStoreEventsServer) SendAndClose(m *StoreEventsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *eventStoreStoreEventsServer) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _EventStore_ServerMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerMestricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).ServerMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventstore.EventStore/ServerMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).ServerMetrics(ctx, req.(*ServerMestricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventStore_ServiceDesc is the grpc.ServiceDesc for EventStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eventstore.EventStore",
	HandlerType: (*EventStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServerMetrics",
			Handler:    _EventStore_ServerMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEvents",
			Handler:       _EventStore_GetEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StoreEvents",
			Handler:       _EventStore_StoreEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "eventstore/event_store.proto",
}
