# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eventstore/event_store.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("eventstore/event_store.proto", :syntax => :proto3) do
    add_message "eventstore.Event" do
      optional :id, :string, 1
      repeated :tags, :string, 2
      optional :content, :bytes, 3
    end
    add_message "eventstore.EventList" do
      repeated :events, :message, 1, "eventstore.Event"
    end
    add_message "eventstore.GetEventRequest" do
      repeated :tags, :string, 2
    end
    add_message "eventstore.StoreEventsResponse" do
      optional :status, :string, 2
    end
    add_message "eventstore.ServerMestricsRequest" do
    end
    add_message "eventstore.ServerMetricsResponse" do
      optional :status, :string, 1
      optional :avg_get_query_duration, :string, 2
      optional :avg_store_duration, :string, 3
      optional :len_events, :int64, 4
      optional :size, :string, 5
    end
  end
end

module Eventstore
  Event = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eventstore.Event").msgclass
  EventList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eventstore.EventList").msgclass
  GetEventRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eventstore.GetEventRequest").msgclass
  StoreEventsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eventstore.StoreEventsResponse").msgclass
  ServerMestricsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eventstore.ServerMestricsRequest").msgclass
  ServerMetricsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eventstore.ServerMetricsResponse").msgclass
end
